version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data1/data/postgresql/data

  airflow-webserver:
    image: airflow-own:v0.1
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - /root/przhang/data-process/dags:/opt/airflow/dags
      - ./logs:/data1/data/airflow/logs
      - ./plugins:/data1/data/airflow/plugins
      - /root/przhang/data-process/data:/opt/airflow/data 
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: webserver

  airflow-scheduler:
    image: airflow-own:v0.1
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - /root/przhang/data-process/dags:/opt/airflow/dags
      - ./logs:/data1/data/airflow/logs
      - ./plugins:/data1/data/airflow/plugins
      - /root/przhang/data-process/data:/opt/airflow/data 
    depends_on:
      - postgres
    command: scheduler

  flask-app:
    image: flask-app:v0.1
    build: .
    network_mode: host
    environment:
      FLASK_ENV: production
    depends_on:
      - postgres

volumes:
  postgres_data: